Session.setDefault("selectedRoomColor", "blue-grey");
Session.setDefault("editingEstimate", false);
Session.setDefault("editingFeature", false);
Session.setDefault("selectedFeatureState", "todo");
Session.setDefault("selectedFeatureEstimate", "?");
Session.setDefault("countingDown", false);
Session.setDefault("timer", App.UI.countdown.timerStart);
Session.setDefault("averageReady", false);
Session.setDefault("chosenEstimation", "?");